# Generated by Django 2.2 on 2019-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_experiment_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='attribute',
            field=models.TextField(blank=True, null=True),
        ),
    ]
