# Generated by Django 2.2 on 2019-10-30 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_experiment_file_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='inner_path',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
